### ISSUE TITLE
is there no way to hide cancel button ?

### ISSUE THREAD

**Issue by IanLaFlair** [iamageo/BeautifulDialog#4]

**Comment by IanLaFlair** [comment]
sorry, if i upgrade to 1.0.2, beautifuldialog turn into unresolved reference

**Comment by iamageo** [comment]
try this, I removed the release prefix:
```gradle
implementation 'com.github.iamageo:beautiful-dialog:1.0.2'
```

see on Jitpack: https://jitpack.io/#iamageo/beautiful-dialog/1.0.2
