### ISSUE TITLE
Cant Resolve build

### ISSUE THREAD

**Issue by stellawills** [iamageo/BeautifulDialog#8]
My App is built on Java not sure this would work, I'm new to app development so permit me.

Can't resolve symbol build in `BeautifulDialog.build(MainActivity. this)`

**Comment by stellawills** [comment]
Cannot Resolve method 'onNegative' in 'MainActivity' also.

**Comment by iamageo** [comment]
Hi @stellawills, this library doesn't work for Java, you can convert your java file to Kotlin as a test and see how it works.
